sudo: required
language: cpp
services:
- docker
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
before_install:
  - sudo apt-get install libboost1.54-all-dev root-system-common libroot-bindings-python5.34 libroot-bindings-python-dev
  - ./.install-dependencies.sh
install:
  - source scripts/ini_excalibur.sh
  - make check
  - make
script:
  - wget http://www-ekp.physik.uni-karlsruhe.de/~berger/files/excalibur-data.root
  - ls -l
  - sed -i 's:/storage/.*root:excalibur-data.root:' test/data.py.json
  - source scripts/ini_merlin.sh
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/x86_64-linux-gnu/root5.34
  - ./scripts/test_excalibur.sh
